# Generated by Django 3.2.8 on 2021-10-24 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
